# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=20)),
                ('devid', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(1, b'Master'), (2, b'EC'), (3, b'Pressure')])),
            ],
        ),
        migrations.CreateModel(
            name='ECModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.BaseModule')),
                ('temperature', models.IntegerField()),
                ('ec1', models.IntegerField()),
                ('ec2', models.IntegerField()),
            ],
            bases=('peil.basemodule',),
        ),
        migrations.CreateModel(
            name='MasterModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.BaseModule')),
                ('angle', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            bases=('peil.basemodule',),
        ),
        migrations.CreateModel(
            name='PressureModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.BaseModule')),
                ('pressure', models.IntegerField()),
            ],
            bases=('peil.basemodule',),
        ),
    ]
