# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0002_auto_20170427_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecmodule',
            options={'verbose_name': 'EC-meting', 'verbose_name_plural': 'EC-metingen'},
        ),
        migrations.AlterModelOptions(
            name='mastermodule',
            options={'verbose_name': 'Toestandsmeting', 'verbose_name_plural': 'Toestandsmetingen'},
        ),
        migrations.AlterModelOptions(
            name='pressuremodule',
            options={'verbose_name': 'Drukmeting', 'verbose_name_plural': 'Drukmetingen'},
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='type',
            field=models.IntegerField(choices=[(2, b'EC'), (3, b'Pressure'), (6, b'Master')]),
        ),
    ]
