# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0003_auto_20170428_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNSSModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.BaseModule')),
                ('gnsstime', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('alt', models.IntegerField()),
                ('vacc', models.IntegerField()),
                ('hacc', models.IntegerField()),
                ('msl', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Positie',
                'verbose_name_plural': 'Posities',
            },
            bases=('peil.basemodule',),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='type',
            field=models.IntegerField(choices=[(1, b'GNSS'), (2, b'EC'), (3, b'Pressure'), (6, b'Master')]),
        ),
    ]
