# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0004_auto_20170505_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnssmodule',
            name='gnsstime',
            field=models.BigIntegerField(),
        ),
    ]
