# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0006_auto_20170507_2125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basemodule',
            unique_together=set([]),
        ),
    ]
