# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_devices(apps, schema_editor):
    Device = apps.get_model('peil', 'Device')
    BaseModule = apps.get_model('peil', 'BaseModule')
    for b in BaseModule.objects.all():
        d, created = Device.objects.get_or_create(serial=b.serial, devid=b.devid)
        if created: 
            print d.devid
        b.device = d
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0007_auto_20170507_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, unique=True)),
                ('devid', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='basemodule',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peil.Device'),
        ),
        migrations.RunPython(create_devices),
    ]
