# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0008_auto_20170507_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodule',
            name='devid',
        ),
        migrations.RemoveField(
            model_name='basemodule',
            name='serial',
        ),
    ]
