# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0009_auto_20170507_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device'),
        ),
    ]
