# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0010_auto_20170507_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw1', models.FloatField(null=True)),
                ('raw2', models.FloatField(null=True)),
                ('value', models.FloatField()),
            ],
        ),
    ]
