# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0011_calibrationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='calibrationdata',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peil.CalibrationSeries'),
            preserve_default=False,
        ),
    ]
