# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0012_auto_20170510_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationseries',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibrationseries',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
