# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0013_auto_20170510_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationseries',
            options={'verbose_name': 'Calibratie reeks', 'verbose_name_plural': 'Calibratie reeksen'},
        ),
        migrations.AddField(
            model_name='device',
            name='cal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peil.CalibrationSeries'),
            preserve_default=False,
        ),
    ]
