# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0014_auto_20170510_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressuremodule',
            old_name='pressure',
            new_name='raw',
        ),
    ]
