# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0015_auto_20170510_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationdata',
            options={'ordering': ('value',), 'verbose_name': 'ijkpunt', 'verbose_name_plural': 'ijkpunten'},
        ),
        migrations.RenameField(
            model_name='calibrationdata',
            old_name='raw1',
            new_name='adc1',
        ),
        migrations.RenameField(
            model_name='ecmodule',
            old_name='ec1',
            new_name='adc1',
        ),
        migrations.RenameField(
            model_name='ecmodule',
            old_name='ec2',
            new_name='adc2',
        ),
        migrations.RemoveField(
            model_name='calibrationdata',
            name='raw2',
        ),
        migrations.AddField(
            model_name='calibrationdata',
            name='adc2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
