# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0017_auto_20170511_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastermodule',
            old_name='pressure',
            new_name='air',
        ),
    ]
