# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0018_auto_20170511_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Peilstok', 'verbose_name_plural': 'Peilstokken'},
        ),
        migrations.AlterModelOptions(
            name='gnssmodule',
            options={'verbose_name': 'Locatie', 'verbose_name_plural': 'Locaties'},
        ),
        migrations.AlterModelOptions(
            name='mastermodule',
            options={'verbose_name': 'Toestand', 'verbose_name_plural': 'Toestand'},
        ),
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='cal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.CalibrationSeries', verbose_name=b'ijkreeks'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devid',
            field=models.CharField(max_length=20, verbose_name=b'naam'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'MAC-adres'),
        ),
    ]
