# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0020_auto_20170514_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecmodule',
            name='position',
        ),
        migrations.RemoveField(
            model_name='pressuremodule',
            name='position',
        ),
        migrations.RenameField(
            model_name='basemodule',
            old_name='base_position',
            new_name='position',
        ),
    ]
