# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0021_auto_20170514_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngleMessage',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.BaseModule')),
                ('angle', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Beweging',
                'verbose_name_plural': 'Bewegingen',
            },
            bases=('peil.basemodule',),
        ),
        migrations.RemoveField(
            model_name='gnssmodule',
            name='gnsstime',
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'GNSS'), (2, b'EC'), (3, b'Pressure'), (5, b'Angle'), (6, b'Master')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
