# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0022_auto_20170529_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
