# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 22:23
from __future__ import unicode_literals

from django.db import migrations
from peil.models import Device
def set_last(apps, schema_editor):
#    Device = apps.get_model('peil', 'Device')
    for dev in Device.objects.all():
        dev.last_seen = dev.last_time()
        dev.save()

class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0023_device_last_seen'),
    ]

    operations = [
        migrations.RunPython(set_last)
    ]
