# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0024_auto_20170612_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=20, verbose_name=b'MAC-adres'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('serial', 'devid')]),
        ),
    ]
