# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0025_auto_20170614_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavPVT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('alt', models.IntegerField()),
                ('msl', models.IntegerField()),
                ('hAcc', models.PositiveIntegerField()),
                ('vAcc', models.PositiveIntegerField()),
                ('numSV', models.PositiveSmallIntegerField()),
                ('PDOP', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UBXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubxfile', models.FileField(upload_to=b'ubx')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device')),
            ],
        ),
        migrations.AddField(
            model_name='navpvt',
            name='ubxfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.UBXFile'),
        ),
    ]
