# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0026_auto_20170614_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navpvt',
            old_name='PDOP',
            new_name='pDOP',
        ),
    ]
