# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0027_auto_20170615_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navpvt',
            options={'verbose_name': 'NAV-PVT message', 'verbose_name_plural': 'NAV-PVT messages'},
        ),
        migrations.AlterModelOptions(
            name='ubxfile',
            options={'verbose_name': 'u-blox bestand', 'verbose_name_plural': 'u-blox bestanden'},
        ),
        migrations.AddField(
            model_name='ubxfile',
            name='start',
            field=models.DateTimeField(null=True, verbose_name=b'Tijdstip eerste observatie'),
        ),
        migrations.AddField(
            model_name='ubxfile',
            name='stop',
            field=models.DateTimeField(null=True, verbose_name=b'Tijdstip laatste observatie'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device', verbose_name=b'peilstok'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'Sensorpositie'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='time',
            field=models.DateTimeField(verbose_name=b'tijdstip'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Geregistreerd'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name=b'Laatste contact'),
        ),
        migrations.AlterField(
            model_name='ecmodule',
            name='temperature',
            field=models.IntegerField(help_text=b'temperatuur in 0.01 graden Celcius'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='alt',
            field=models.IntegerField(help_text=b'hoogte ten opzichte van ellipsoid in mm', verbose_name=b'ellipsoid'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='hacc',
            field=models.IntegerField(help_text=b'horizontale nauwkeurigheid in mm', verbose_name=b'horizontale nauwkeurigheid'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='lat',
            field=models.IntegerField(verbose_name=b'breedtegraad'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='lon',
            field=models.IntegerField(verbose_name=b'lengtegraad'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='msl',
            field=models.IntegerField(help_text=b'hoogte ten opzichte van zeeniveau in mm', verbose_name=b'zeeniveau'),
        ),
        migrations.AlterField(
            model_name='gnssmodule',
            name='vacc',
            field=models.IntegerField(help_text=b'vertikale nauwkeurigheid in mm', verbose_name=b'vertikale nauwkeurigheid'),
        ),
        migrations.AlterField(
            model_name='mastermodule',
            name='air',
            field=models.IntegerField(verbose_name=b'Luchtdruk'),
        ),
        migrations.AlterField(
            model_name='mastermodule',
            name='angle',
            field=models.IntegerField(verbose_name=b'inclinatiehoek'),
        ),
        migrations.AlterField(
            model_name='mastermodule',
            name='battery',
            field=models.IntegerField(verbose_name=b'Batterijspanning'),
        ),
        migrations.AlterField(
            model_name='mastermodule',
            name='total',
            field=models.PositiveSmallIntegerField(verbose_name=b'maximum aantal sensoren'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='alt',
            field=models.IntegerField(help_text=b'Hoogte tov ellipsoide in mm', verbose_name=b'Ellipsoide'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='hAcc',
            field=models.PositiveIntegerField(help_text=b'Horizontale nauwkeurigheid in mm', verbose_name=b'hAcc'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'Breedtegraad'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'Lengtegraad'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='msl',
            field=models.IntegerField(help_text=b'Hoogte tov zeeniveau in mm', verbose_name=b'Zeeniveau'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='numSV',
            field=models.PositiveSmallIntegerField(help_text=b'Aantal zichtbare satellieten', verbose_name=b'satellieten'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='pDOP',
            field=models.DecimalField(decimal_places=2, help_text=b'Dilution of Precision', max_digits=10, verbose_name=b'DOP'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='timestamp',
            field=models.DateTimeField(verbose_name=b'Tijdstip'),
        ),
        migrations.AlterField(
            model_name='navpvt',
            name='vAcc',
            field=models.PositiveIntegerField(help_text=b'verticale nauwkeurigheid in mm', verbose_name=b'vAcc'),
        ),
    ]
