# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0029_auto_20170616_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTKConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('convbin', models.CharField(max_length=200)),
                ('rnx2rtkp', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'RTKLIB configuratie',
                'verbose_name_plural': 'RTKLIB configuraties',
            },
        ),
    ]
