# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0030_rtkconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtkconfig',
            name='convbin_args',
            field=models.CharField(default='ars', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtkconfig',
            name='rnx2rtkp_args',
            field=models.CharField(default='args', max_length=200),
            preserve_default=False,
        ),
    ]
