# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('peil', '0031_auto_20170618_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngleSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.Sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.sensor',),
        ),
        migrations.CreateModel(
            name='BatterySensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.Sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.sensor',),
        ),
        migrations.CreateModel(
            name='ECSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.Sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.sensor',),
        ),
        migrations.CreateModel(
            name='GNSS_Sensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.Sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.sensor',),
        ),
        migrations.CreateModel(
            name='LoraMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name=b'tijdstip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.Sensor')),
                ('offset', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.sensor',),
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'sensoren'},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='type',
        ),
        migrations.AddField(
            model_name='sensor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_peil.sensor_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'Sensorpositie'),
        ),
        migrations.AlterField(
            model_name='fix',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.GNSS_Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device', verbose_name=b'Peilstok'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='distance',
            field=models.IntegerField(default=0, help_text=b'afstand tov onderkant mm', verbose_name=b'afstand'),
        ),
        migrations.CreateModel(
            name='ECMessage',
            fields=[
                ('loramessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.LoraMessage')),
                ('temperature', models.IntegerField(help_text=b'temperatuur in 0.01 graden Celcius')),
                ('adc1', models.IntegerField()),
                ('adc2', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.loramessage',),
        ),
        migrations.CreateModel(
            name='InclinationMessage',
            fields=[
                ('loramessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.LoraMessage')),
                ('angle', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.loramessage',),
        ),
        migrations.CreateModel(
            name='LocationMessage',
            fields=[
                ('loramessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.LoraMessage')),
                ('lat', models.IntegerField(verbose_name=b'breedtegraad')),
                ('lon', models.IntegerField(verbose_name=b'lengtegraad')),
                ('alt', models.IntegerField(help_text=b'hoogte ten opzichte van ellipsoid in mm', verbose_name=b'ellipsoid')),
                ('vacc', models.IntegerField(help_text=b'vertikale nauwkeurigheid in mm', verbose_name=b'vertikale nauwkeurigheid')),
                ('hacc', models.IntegerField(help_text=b'horizontale nauwkeurigheid in mm', verbose_name=b'horizontale nauwkeurigheid')),
                ('msl', models.IntegerField(help_text=b'hoogte ten opzichte van zeeniveau in mm', verbose_name=b'zeeniveau')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.loramessage',),
        ),
        migrations.CreateModel(
            name='PressureMessage',
            fields=[
                ('loramessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.LoraMessage')),
                ('adc', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.loramessage',),
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('loramessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peil.LoraMessage')),
                ('battery', models.PositiveSmallIntegerField(verbose_name=b'batterijniveau')),
            ],
            options={
                'abstract': False,
            },
            bases=('peil.loramessage',),
        ),
        migrations.AddField(
            model_name='loramessage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_peil.loramessage_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='loramessage',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Sensor'),
        ),
    ]
