# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0032_auto_20170626_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anglesensor',
            options={'verbose_name': 'Inclinometer', 'verbose_name_plural': 'Inclinometers'},
        ),
        migrations.AlterModelOptions(
            name='batterysensor',
            options={'verbose_name': 'Batterijspanning', 'verbose_name_plural': 'Batterijspanning'},
        ),
        migrations.AlterModelOptions(
            name='ecsensor',
            options={'verbose_name': 'EC-Sensor', 'verbose_name_plural': 'EC-sensoren'},
        ),
        migrations.AlterModelOptions(
            name='gnss_sensor',
            options={'verbose_name': 'GPS', 'verbose_name_plural': 'GPS'},
        ),
        migrations.AlterModelOptions(
            name='pressuresensor',
            options={'verbose_name': 'Druksensor', 'verbose_name_plural': 'druksensoren'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'sensoren'},
        ),
    ]
