# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0033_auto_20170627_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecmessage',
            options={'verbose_name': 'EC-meting', 'verbose_name_plural': 'EC-metingen'},
        ),
        migrations.AlterModelOptions(
            name='inclinationmessage',
            options={'verbose_name': 'Hoekmeting', 'verbose_name_plural': 'Hoekmetingen'},
        ),
        migrations.AlterModelOptions(
            name='locationmessage',
            options={'verbose_name': 'Plaatsbepaling', 'verbose_name_plural': 'Plaatsbepalingen'},
        ),
        migrations.AlterModelOptions(
            name='pressuremessage',
            options={'verbose_name': 'Drukmeting', 'verbose_name_plural': 'Drukmetingen'},
        ),
        migrations.AlterModelOptions(
            name='statusmessage',
            options={'verbose_name': 'Batterijmeting', 'verbose_name_plural': 'Batterijmetingen'},
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='battery',
            field=models.IntegerField(verbose_name=b'batterijniveau'),
        ),
    ]
