# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0034_auto_20170627_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ident',
            field=models.CharField(default=b'sensor', max_length=50),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='offset',
            field=models.FloatField(default=0.0),
        ),
    ]
