# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0035_auto_20170628_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationdata',
            name='series',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cal',
        ),
        migrations.DeleteModel(
            name='CalibrationData',
        ),
        migrations.DeleteModel(
            name='CalibrationSeries',
        ),
    ]
