# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0036_auto_20170628_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecsensor',
            name='adc1_coef',
            field=models.CharField(default=b'-1.24962278e-01,7.51304212e+02,-6.42625003e+05,-3.31128125e+03', max_length=200, verbose_name=b'Coefficienten ring1'),
        ),
        migrations.AddField(
            model_name='ecsensor',
            name='adc1_limits',
            field=models.CharField(default=b'3400,4094', max_length=50, verbose_name=b'limieten ring1'),
        ),
        migrations.AddField(
            model_name='ecsensor',
            name='adc2_coef',
            field=models.CharField(default=b'-2.72687329e+01,2.07166387e+05,-3.88755659e+08,-3.50129229e+03', max_length=200, verbose_name=b'Coefficienten ring2'),
        ),
        migrations.AddField(
            model_name='ecsensor',
            name='adc2_limits',
            field=models.CharField(default=b'3600,4094', max_length=50, verbose_name=b'limieten ring2'),
        ),
        migrations.AddField(
            model_name='ecsensor',
            name='tempfactor',
            field=models.FloatField(default=0.0246534878, help_text=b'factor voor conversie naar 25 oC', verbose_name=b'factor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device', verbose_name=b'peilstok'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ident',
            field=models.CharField(default=b'sensor', max_length=50, verbose_name=b'sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'positie'),
        ),
    ]
