# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0038_ecsensor_ec_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anglemessage',
            name='basemodule_ptr',
        ),
        migrations.RemoveField(
            model_name='basemodule',
            name='device',
        ),
        migrations.RemoveField(
            model_name='ecmodule',
            name='basemodule_ptr',
        ),
        migrations.RemoveField(
            model_name='gnssmodule',
            name='basemodule_ptr',
        ),
        migrations.RemoveField(
            model_name='mastermodule',
            name='basemodule_ptr',
        ),
        migrations.RemoveField(
            model_name='pressuremodule',
            name='basemodule_ptr',
        ),
        migrations.AlterModelOptions(
            name='loramessage',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc1_coef',
            field=models.CharField(default=b'[-1.24962278e-01,   7.51304212e+02,  -6.42625003e+05,  -3.31128125e+03]', max_length=200, verbose_name=b'Coefficienten ring1'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc1_limits',
            field=models.CharField(default=b'[3400,4094]', max_length=50, verbose_name=b'bereik ring1'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc2_coef',
            field=models.CharField(default=b'[-2.72687329e+01,   2.07166387e+05,  -3.88755659e+08,  -3.50129229e+03]', max_length=200, verbose_name=b'Coefficienten ring2'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc2_limits',
            field=models.CharField(default=b'[3600,4094]', max_length=50, verbose_name=b'bereik ring2'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='ec_range',
            field=models.CharField(default=b'[700,30000]', max_length=50, verbose_name=b'bereik'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='distance',
            field=models.IntegerField(default=0, help_text=b'afstand tov antenne', verbose_name=b'afstand'),
        ),
        migrations.DeleteModel(
            name='AngleMessage',
        ),
        migrations.DeleteModel(
            name='BaseModule',
        ),
        migrations.DeleteModel(
            name='ECModule',
        ),
        migrations.DeleteModel(
            name='GNSSModule',
        ),
        migrations.DeleteModel(
            name='MasterModule',
        ),
        migrations.DeleteModel(
            name='PressureModule',
        ),
    ]
