# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 20:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0039_auto_20170701_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text=b'tijdstip van inmeten', verbose_name=b'tijdstip')),
                ('surveyor', models.CharField(help_text=b'naam van waarnemer', max_length=100, verbose_name=b'waarnemer')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text=b'locatie in Rijksdriehoekstelsel coorinaten', srid=28992, verbose_name=b'locatie')),
                ('altitude', models.DecimalField(blank=True, decimal_places=3, help_text=b'hoogte van de deksel in m tov NAP', max_digits=10, null=True, verbose_name=b'hoogte')),
                ('vacc', models.PositiveIntegerField(blank=True, help_text=b'vertikale nauwkeurigheid in mm', null=True, verbose_name=b'vertikale nauwkeurigheid')),
                ('hacc', models.PositiveIntegerField(blank=True, help_text=b'horizontale naukeurigheid in mm', null=True, verbose_name=b'horizontale naukeurigheid')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.Device', verbose_name=b'peilstok')),
            ],
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc2_limits',
            field=models.CharField(default=b'[3590,4094]', max_length=50, verbose_name=b'bereik ring2'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='ec_range',
            field=models.CharField(default=b'[700,40000]', max_length=50, verbose_name=b'bereik'),
        ),
    ]
