# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0040_auto_20170702_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('devid',), 'verbose_name': 'Peilstok', 'verbose_name_plural': 'Peilstokken'},
        ),
        migrations.AlterModelOptions(
            name='loramessage',
            options={'ordering': ['-time'], 'verbose_name': 'LoRa bericht', 'verbose_name_plural': 'LoRa berichten'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default=b'-', max_length=10),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc1_coef',
            field=models.CharField(default=b'[  3.20095703e+00,  -2.33432625e+04,   4.29865790e+07, -3.28578862e+03]', max_length=200, verbose_name=b'Coefficienten ring1'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc1_limits',
            field=models.CharField(default=b'[3300,4094]', max_length=50, verbose_name=b'bereik ring1'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc2_coef',
            field=models.CharField(default=b'[ -1.43038274e+01,   9.88206493e+04,  -1.61772418e+08, -3.34497296e+03]', max_length=200, verbose_name=b'Coefficienten ring2'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='adc2_limits',
            field=models.CharField(default=b'[3500,4094]', max_length=50, verbose_name=b'bereik ring2'),
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='ec_range',
            field=models.CharField(default=b'[700,50000]', max_length=50, verbose_name=b'bereik'),
        ),
    ]
