# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0041_auto_20170704_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('position', 'ident'), 'verbose_name': 'Sensor', 'verbose_name_plural': 'sensoren'},
        ),
    ]
