# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0042_auto_20170704_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='length',
            field=models.IntegerField(help_text=b'Totale lengte peilstok in mm', null=True, verbose_name=b'Lengte'),
        ),
    ]
