# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0043_device_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='displayname',
            field=models.CharField(default='default', max_length=20, verbose_name=b'naam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='devid',
            field=models.CharField(max_length=20, verbose_name=b'identificatie'),
        ),
    ]
