# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 11:46
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0046_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('device', 'order', 'photo'), 'verbose_name': 'foto'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to=b'photos'),
        ),
    ]
