# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0047_auto_20170806_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTKSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name=b'Tijdstip van fix')),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'lengtegraad (deg)')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'breedtegraad (deg)')),
                ('alt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=b'hoogte tov ellipsoide (m)')),
                ('q', models.PositiveSmallIntegerField(verbose_name=b'Type of fix')),
                ('ns', models.PositiveSmallIntegerField(verbose_name=b'Aantal satellieten')),
                ('sde', models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Standaard deviatie in x-richting (m)')),
                ('sdn', models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Standaard deviatie in y-richting (m)')),
                ('sdu', models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Standaard deviatie in hoogte (m)')),
                ('x', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=b'x-coordinaat (m)')),
                ('y', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=b'y-coordinaat (m)')),
                ('z', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=b'hoogte tov NAP (m)')),
                ('ubx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peil.UBXFile')),
            ],
        ),
        migrations.RemoveField(
            model_name='fix',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='RTKConfig',
        ),
        migrations.RenameField(
            model_name='navpvt',
            old_name='ubxfile',
            new_name='ubx',
        ),
        migrations.DeleteModel(
            name='Fix',
        ),
    ]
