# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0048_auto_20170903_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtksolution',
            name='x',
        ),
        migrations.RemoveField(
            model_name='rtksolution',
            name='y',
        ),
        migrations.RemoveField(
            model_name='rtksolution',
            name='z',
        ),
        migrations.AlterField(
            model_name='rtksolution',
            name='q',
            field=models.PositiveSmallIntegerField(choices=[(0, b'None'), (1, b'Fixed'), (2, b'Float'), (4, b'DGPS'), (5, b'Single'), (6, b'PPP')], verbose_name=b'Type of fix'),
        ),
        migrations.AlterField(
            model_name='rtksolution',
            name='time',
            field=models.DateTimeField(verbose_name=b'Tijdstip'),
        ),
    ]
