# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0049_auto_20170903_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rtksolution',
            options={'verbose_name': 'RTK Fix', 'verbose_name_plural': 'RTK Fixes'},
        ),
        migrations.AlterUniqueTogether(
            name='rtksolution',
            unique_together=set([('ubx', 'time')]),
        ),
    ]
