# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0050_auto_20170903_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtksolution',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'x-coordinaat (m)'),
        ),
        migrations.AddField(
            model_name='rtksolution',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'y-coordinaat (m)'),
        ),
        migrations.AddField(
            model_name='rtksolution',
            name='z',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name=b'hoogte tov NAP (m)'),
        ),
        migrations.AlterField(
            model_name='rtksolution',
            name='sde',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Stdev x (m)'),
        ),
        migrations.AlterField(
            model_name='rtksolution',
            name='sdn',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Stdev y (m)'),
        ),
        migrations.AlterField(
            model_name='rtksolution',
            name='sdu',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name=b'Stdev z (m)'),
        ),
        migrations.AlterField(
            model_name='ubxfile',
            name='start',
            field=models.DateTimeField(null=True, verbose_name=b'Eerste observatie'),
        ),
        migrations.AlterField(
            model_name='ubxfile',
            name='stop',
            field=models.DateTimeField(null=True, verbose_name=b'Laatste observatie'),
        ),
    ]
