# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0051_auto_20170903_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ispopup',
            field=models.BooleanField(default=False, help_text=b'Wordt getoond in popup venster op de kaart'),
        ),
        migrations.AlterField(
            model_name='ubxfile',
            name='start',
            field=models.DateTimeField(null=True, verbose_name=b'begin'),
        ),
        migrations.AlterField(
            model_name='ubxfile',
            name='stop',
            field=models.DateTimeField(null=True, verbose_name=b'einde'),
        ),
    ]
