# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0052_auto_20171007_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ispopup',
            field=models.BooleanField(default=False, help_text=b'Wordt getoond in popup venster op de kaart', verbose_name=b'popup'),
        ),
    ]
