# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0054_auto_20171206_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devid',
            field=models.CharField(max_length=40, verbose_name=b'identificatie'),
        ),
    ]
