# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peil', '0055_auto_20171206_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField(blank=True, default=None, null=True)),
                ('max', models.FloatField(blank=True, default=None, null=True)),
                ('mean', models.FloatField(blank=True, default=None, null=True)),
                ('nobs', models.IntegerField(blank=True, default=None, null=True)),
                ('variance', models.FloatField(blank=True, default=None, null=True)),
                ('skewness', models.FloatField(blank=True, default=None, null=True)),
                ('kurtosis', models.FloatField(blank=True, default=None, null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peil.Sensor')),
            ],
        ),
        migrations.AlterField(
            model_name='ecsensor',
            name='ec_range',
            field=models.CharField(default=b'[700,35000]', max_length=50, verbose_name=b'bereik'),
        ),
    ]
